INSERT INTO MEMBER (ID, MID, MPASS, MNAME, MPHONE, MEMAIL, MDOB)
	VALUES(MEMBER_SEQ.NEXTVAL, '아이디1', '비밀번호1', '이름1', '111-1111-1111', '메일1@test.com', '1111-11-11');

UPDATE MEMBER
SET MID = '아이디4',
    MPASS = '비밀번호4',
    MNAME = '이름4',
    MPHONE = '전화번호4',
    MEMAIL = '이메일4',
    MDOB = '4444-44-44'
WHERE ID = 4;

DELETE MEMBER WHERE ID = 4;

SELECT * FROM MEMBER WHERE MID = '아이디2';

SELECT COUNT(*) cnt FROM MEMBER WHERE MID = '아이디2';

INSERT INTO BOOK (BID, BTITLE, BAUTHOR, BCATEGORY)
	VALUES(BOOK_SEQ.NEXTVAL, '책제목1', '책저자1', '소설');

UPDATE BOOK
SET	BTITLE = '책제목2',
	BAUTHOR = '책저자2',
	BCATEGORY = '수필'
WHERE BID = 2;

DELETE BOOK WHERE BID = 2;

INSERT INTO LOAN (LID, ID, BID, RENT_DATE) VALUES (LOAN_SEQ.NEXTVAL, '2', '1', sysdate);

UPDATE LOAN SET RETURN_DATE = sysdate WHERE LID = 1;

SELECT COUNT(*) FROM LOAN WHERE LID = 1;